# Generated by Django 5.2.1 on 2025-06-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_field1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='extra_field2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
