# Generated by Django 5.2.1 on 2025-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_extra_field1_question_extra_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('advanced', 'Advanced')], default='foundation', max_length=20),
        ),
    ]
