# Generated by Django 5.2.2 on 2025-06-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_topic_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='extra_field1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='extra_field2',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='For MCQ: single letter (a/b/c/d). For MSQ: comma-separated letters (a,b,c)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
