# Generated by Django 5.2.2 on 2025-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_extra_field1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
