# Generated by Django 5.2.3 on 2025-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_explanation'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='questions.subtopic'),
        ),
    ]
