# Generated by Django 5.2.1 on 2025-06-20 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpreference_subtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_question_papers',
            field=models.PositiveIntegerField(default=10, help_text='Max question papers this user can generate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_sub_users',
            field=models.PositiveIntegerField(default=0, help_text='Max users this admin can create (school_admin only)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('school_admin', 'School Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
